### ISSUE TITLE
[请求帮助]关于端口和IP的一些配置文件

### ISSUE THREAD

**Issue by Akimio521** [cym1102/nginxWebUI#128]
比如我用a反向代了b服务器，我用c访问通过a反向代理的b服务，但是b服务器获取到的IP是a的，认为是a在访问他，其实我想让b获取到的是c的ip

还是刚刚我举例的情况，假设b服务的开放的端口是3000，我通过反向代理后其实是通过5000端口在访问b，但是b仍然认为是a在通过3000端口访问他，所以在设置跳转url时设置的端口是3000，我通过c访问后就变成了访问了a的3000端口，但问题是a上的3000端口并没有架设对应的服务，就导致了请求失败

因为我没有学过nginx.conf的详细配置教程，希望大佬教一我应该如何配置模板才能快速部署多个可以正确访问的反向代理代理配置

**Comment by cym1102** [comment]
配location的时候, 勾上Host参数应该就可以了



***@***.***
 
发件人： 秋澪Akimio
发送时间： 2024-02-26 17:14
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] [请求帮助]关于端口和IP的一些配置文件 (Issue #128)
比如我用a反向代了b服务器，我用c访问通过a反向代理的b服务，但是b服务器获取到的IP是a的，认为是a在访问他，其实我想让b获取到的是c的ip
还是刚刚我举例的情况，假设b服务的开放的端口是3000，我通过反向代理后其实是通过5000端口在访问b，但是b仍然认为是a在通过3000端口访问他，所以在设置跳转url时设置的端口是3000，我通过c访问后就变成了访问了a的3000端口，但问题是a上的3000端口并没有架设对应的服务，就导致了请求失败
因为我没有学过nginx.conf的详细配置教程，希望大佬教一我应该如何配置模板才能快速部署多个可以正确访问的反向代理代理配置

**Comment by Akimio521** [comment]
b应用获取到的是docker network的网关地址（172.18.0.1）

**Comment by cym1102** [comment]
那你用的应用程序可能获取ip的方式并不标准, 你查查你的应用程序用的哪个host参数获取的ip, 然后你得用额外参数专门的去配这个Host


***@***.***
 
发件人： 秋澪Akimio
发送时间： 2024-02-26 17:28
收件人： cym1102/nginxWebUI
抄送： cym1102; Comment
主题： Re: [cym1102/nginxWebUI] [请求帮助]关于端口和IP的一些配置文件 (Issue #128)
配location的时候, 勾上Host参数应该就可以了
@.***
发件人： 秋澪Akimio
发送时间： 2024-02-26 17:14
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] [请求帮助]关于端口和IP的一些配置文件 (Issue #128)
比如我用a反向代了b服务器，我用c访问通过a反向代理的b服务，但是b服务器获取到的IP是a的，认为是a在访问他，其实我想让b获取到的是c的ip
还是刚刚我举例的情况，假设b服务的开放的端口是3000，我通过反向代理后其实是通过5000端口在访问b，但是b仍然认为是a在通过3000端口访问他，所以在设置跳转url时设置的端口是3000，我通过c访问后就变成了访问了a的3000端口，但问题是a上的3000端口并没有架设对应的服务，就导致了请求失败
因为我没有学过nginx.conf的详细配置教程，希望大佬教一我应该如何配置模板才能快速部署多个可以正确访问的反向代理代理配置
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: @.***>
钩上Host参数并且设置为$host获取的还是docker网络的IP（我的nginxwebui的网络选择的是自己新建的docker网络）

**Comment by cym1102** [comment]
web应用就是这样, 你永远不知道用户用的什么设备在上网, 你拿到的ip不一定可靠



***@***.***
 
发件人： 秋澪Akimio
发送时间： 2024-02-26 17:30
收件人： cym1102/nginxWebUI
抄送： cym1102; Comment
主题： Re: [cym1102/nginxWebUI] [请求帮助]关于端口和IP的一些配置文件 (Issue #128)
b应用获取到的是docker network的网关地址（172.18.0.1）
