### ISSUE TITLE
申请cloudflare证书失败

### ISSUE THREAD

**Issue by mengluo04** [cym1102/nginxWebUI#134]
天了邮箱和key，cloudflare的两个key都试过，申请结果显示：
sh /home/software/nginxWebui/.acme.sh/acme.sh --issue --dns dns_cf -d shuangsheng0513.cn --keylength 2048 --server letsencrypt
申请失败
[Mon Mar 25 07:06:00 PM CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Mar 25 07:06:00 PM CST 2024] Creating domain key
[Mon Mar 25 07:06:00 PM CST 2024] The domain key is here: /home/software/nginxWebui//.acme.sh/shuangsheng0513.cn/shuangsheng0513.cn.key
[Mon Mar 25 07:06:00 PM CST 2024] Single domain='shuangsheng0513.cn'
[Mon Mar 25 07:06:00 PM CST 2024] Getting domain auth token for each domain
[Mon Mar 25 07:06:03 PM CST 2024] Getting webroot for domain='shuangsheng0513.cn'
[Mon Mar 25 07:06:03 PM CST 2024] Adding txt value: 5rBaj_Qj5N7Zsbm_3TbY4gMormtSGSzbd4FOxIv3a7E for domain: _acme-challenge.shuangsheng0513.cn
是需要什么额外的前提吗，没找到相关的文档

**Comment by cym1102** [comment]
到群里问问呗，群里有cf用户申请成功过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月25日(周一) 晚上7:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 申请cloudflare证书失败 (Issue #134)




 
天了邮箱和key，cloudflare的两个key都试过，申请结果显示：
 sh /home/software/nginxWebui/.acme.sh/acme.sh --issue --dns dns_cf -d shuangsheng0513.cn --keylength 2048 --server letsencrypt
 申请失败
 [Mon Mar 25 07:06:00 PM CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
 [Mon Mar 25 07:06:00 PM CST 2024] Creating domain key
 [Mon Mar 25 07:06:00 PM CST 2024] The domain key is here: /home/software/nginxWebui//.acme.sh/shuangsheng0513.cn/shuangsheng0513.cn.key
 [Mon Mar 25 07:06:00 PM CST 2024] Single domain='shuangsheng0513.cn'
 [Mon Mar 25 07:06:00 PM CST 2024] Getting domain auth token for each domain
 [Mon Mar 25 07:06:03 PM CST 2024] Getting webroot for domain='shuangsheng0513.cn'
 [Mon Mar 25 07:06:03 PM CST 2024] Adding txt value: 5rBaj_Qj5N7Zsbm_3TbY4gMormtSGSzbd4FOxIv3a7E for domain: _acme-challenge.shuangsheng0513.cn
 是需要什么额外的前提吗，没找到相关的文档

**Comment by mengluo04** [comment]
> 到群里问问呗，群里有cf用户申请成功过
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月25日(周一) 晚上7:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 申请cloudflare证书失败 (Issue #134) 天了邮箱和key，cloudflare的两个key都试过，申请结果显示： sh /home/software/nginxWebui/.acme.sh/acme.sh --issue --dns dns_cf -d shuangsheng0513.cn --keylength 2048 --server letsencrypt 申请失败 [Mon Mar 25 07:06:00 PM CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory [Mon Mar 25 07:06:00 PM CST 2024] Creating domain key [Mon Mar 25 07:06:00 PM CST 2024] The domain key is here: /home/software/nginxWebui//.acme.sh/shuangsheng0513.cn/shuangsheng0513.cn.key [Mon Mar 25 07:06:00 PM CST 2024] Single domain='shuangsheng0513.cn' [Mon Mar 25 07:06:00 PM CST 2024] Getting domain auth token for each domain [Mon Mar 25 07:06:03 PM CST 2024] Getting webroot for domain='shuangsheng0513.cn' [Mon Mar 25 07:06:03 PM CST 2024] Adding txt value: 5rBaj_Qj5N7Zsbm_3TbY4gMormtSGSzbd4FOxIv3a7E for domain: _acme-challenge.shuangsheng0513.cn 是需要什么额外的前提吗，没找到相关的文档 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

1群还是2群

**Comment by cym1102** [comment]
1600多人的那个大群



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月25日(周一) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 申请cloudflare证书失败 (Issue #134)




  
到群里问问呗，群里有cf用户申请成功过
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月25日(周一) 晚上7:06 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 申请cloudflare证书失败 (Issue #134) 天了邮箱和key，cloudflare的两个key都试过，申请结果显示： sh /home/software/nginxWebui/.acme.sh/acme.sh --issue --dns dns_cf -d shuangsheng0513.cn --keylength 2048 --server letsencrypt 申请失败 [Mon Mar 25 07:06:00 PM CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory [Mon Mar 25 07:06:00 PM CST 2024] Creating domain key [Mon Mar 25 07:06:00 PM CST 2024] The domain key is here: /home/software/nginxWebui//.acme.sh/shuangsheng0513.cn/shuangsheng0513.cn.key [Mon Mar 25 07:06:00 PM CST 2024] Single domain='shuangsheng0513.cn' [Mon Mar 25 07:06:00 PM CST 2024] Getting domain auth token for each domain [Mon Mar 25 07:06:03 PM CST 2024] Getting webroot for domain='shuangsheng0513.cn' [Mon Mar 25 07:06:03 PM CST 2024] Adding txt value: 5rBaj_Qj5N7Zsbm_3TbY4gMormtSGSzbd4FOxIv3a7E for domain: _acme-challenge.shuangsheng0513.cn 是需要什么额外的前提吗，没找到相关的文档 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
1群还是2群

**Comment by mengluo04** [comment]
加了
