### ISSUE TITLE
切换到远程服务器后，试图下载远程服务器上的证书时，不会打开下载窗口，而是打开新页面

### ISSUE THREAD

**Issue by OuroborosCaster** [cym1102/nginxWebUI#140]

**Comment by cym1102** [comment]
打开的新页面显示什么内容？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月6日(周六) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 切换到远程服务器后，试图下载远程服务器上的证书时，不会打开下载窗口，而是打开新页面 (Issue #140)

**Comment by OuroborosCaster** [comment]
> 打开的新页面显示什么内容？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月6日(周六) 上午9:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 切换到远程服务器后，试图下载远程服务器上的证书时，不会打开下载窗口，而是打开新页面 (Issue #140) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

PK开头的乱码

**Comment by cym1102** [comment]
哦，是content-type没设置好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月6日(周六) 上午9:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 切换到远程服务器后，试图下载远程服务器上的证书时，不会打开下载窗口，而是打开新页面 (Issue #140)




  
打开的新页面显示什么内容？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月6日(周六) 上午9:16 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 切换到远程服务器后，试图下载远程服务器上的证书时，不会打开下载窗口，而是打开新页面 (Issue #140) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
PK开头的乱码
