### ISSUE TITLE
反向代理中配置重定向的时候用户决定是否需要原路径

### ISSUE THREAD

**Issue by diaodeng** [cym1102/nginxWebUI#149]
帮忙在配置重定向的时候增加个选项，用户自己决定是否追加原路径（$request_uri）；
只有一个域名，想用一个端口作为总入口的跳转路径，输入不同路径跳转到不同的服务（各个服务完全独立，通过端口区分的），不需要原来路径；就是端口太多不方便记忆，想通过一个固定端口加路径名来跳其他端口的服务；现在每次重新生效配置时都需要手动删除$request_uri。

**Comment by cym1102** [comment]
你可以用参数模板解决这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月7日(周五) 上午7:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149)




 
帮忙在配置重定向的时候增加个选项，用户自己决定是否追加原路径（$request_uri）；
 只有一个域名，想用一个端口作为总入口的跳转路径，输入不同路径跳转到不同的服务（各个服务完全独立，通过端口区分的），不需要原来路径；就是端口太多不方便记忆，想通过一个固定端口加路径名来跳其他端口的服务；现在每次重新生效配置时都需要手动删除$request_uri。

**Comment by diaodeng** [comment]
> 你可以用参数模板解决这个问题
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月7日(周五) 上午7:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149) 帮忙在配置重定向的时候增加个选项，用户自己决定是否追加原路径（$request_uri）； 只有一个域名，想用一个端口作为总入口的跳转路径，输入不同路径跳转到不同的服务（各个服务完全独立，通过端口区分的），不需要原来路径；就是端口太多不方便记忆，想通过一个固定端口加路径名来跳其他端口的服务；现在每次重新生效配置时都需要手动删除$request_uri。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

确实模板参数可以解决这个问题，但是每个需要重定向的地址都得单独建一个模板，而且在反向代理的页面中不方便查看代理到哪里去了

**Comment by cym1102** [comment]
明白了 , 等我有空做



***@***.***
 
发件人： diaodeng
发送时间： 2024-06-07 09:52
收件人： cym1102/nginxWebUI
抄送： cym1102; Comment
主题： Re: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149)
你可以用参数模板解决这个问题
…
---原始邮件--- 发件人: @.> 发送时间: 2024年6月7日(周五) 上午7:49 收件人: @.>; 抄送: @.>; 主题: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149) 帮忙在配置重定向的时候增加个选项，用户自己决定是否追加原路径（$request_uri）； 只有一个域名，想用一个端口作为总入口的跳转路径，输入不同路径跳转到不同的服务（各个服务完全独立，通过端口区分的），不需要原来路径；就是端口太多不方便记忆，想通过一个固定端口加路径名来跳其他端口的服务；现在每次重新生效配置时都需要手动删除$request_uri。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
确实模板参数可以解决这个问题，但是每个需要重定向的地址都得单独建一个模板，而且在反向代理的页面中不方便查看代理到哪里去了
image.png (view on web)

**Comment by sleikang** [comment]
> 明白了 , 等我有空做 ***@***.*** 发件人： diaodeng 发送时间： 2024-06-07 09:52 收件人： cym1102/nginxWebUI 抄送： cym1102; Comment 主题： Re: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149) 你可以用参数模板解决这个问题 … ---原始邮件--- 发件人: @.> 发送时间: 2024年6月7日(周五) 上午7:49 收件人: @.>; 抄送: @.>; 主题: [cym1102/nginxWebUI] 反向代理中配置重定向的时候用户决定是否需要原路径 (Issue #149) 帮忙在配置重定向的时候增加个选项，用户自己决定是否追加原路径（$request_uri）； 只有一个域名，想用一个端口作为总入口的跳转路径，输入不同路径跳转到不同的服务（各个服务完全独立，通过端口区分的），不需要原来路径；就是端口太多不方便记忆，想通过一个固定端口加路径名来跳其他端口的服务；现在每次重新生效配置时都需要手动删除$request_uri。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 确实模板参数可以解决这个问题，但是每个需要重定向的地址都得单独建一个模板，而且在反向代理的页面中不方便查看代理到哪里去了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

可以借鉴下Lucky 他那个批量配置很方便 就是同一个监听端口可以直接配置多个不同的域名

**Comment by cym1102** [comment]
4.1.5解决此问题
