### ISSUE TITLE
证书界面错位

### ISSUE THREAD

**Issue by web-xiaxia** [cym1102/nginxWebUI#157]
<img width="1328" alt="image" src="https://github.com/cym1102/nginxWebUI/assets/10164282/07b9eb81-d2bf-41da-adbe-ae25635748d2">

**Comment by cym1102** [comment]
这啥浏览器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月2日(周二) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 证书界面错位 (Issue #157)




 image.png (view on web)

**Comment by web-xiaxia** [comment]
> 这啥浏览器
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月2日(周二) 晚上6:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 证书界面错位 (Issue #157) image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谷歌浏览器 m1 最新版

**Comment by cym1102** [comment]
好的我复现一下



***@***.***
 
发件人： 下下
发送时间： 2024-07-02 22:35
收件人： cym1102/nginxWebUI
抄送： cym1102; Comment
主题： Re: [cym1102/nginxWebUI] 证书界面错位 (Issue #157)
这啥浏览器
…
---原始邮件--- 发件人: @.> 发送时间: 2024年7月2日(周二) 晚上6:40 收件人: @.>; 抄送: @.>; 主题: [cym1102/nginxWebUI] 证书界面错位 (Issue #157) image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
谷歌浏览器 m1 最新版

**Comment by cym1102** [comment]
你一个证书域名太多了, 为啥不用泛域名
