### ISSUE TITLE
放开 tcp 反向代理的限制

### ISSUE THREAD

**Issue by ZhReimu** [cym1102/nginxWebUI#160]
现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 `proxy_pass $variable`, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置
![QQ_1721302618332](https://github.com/user-attachments/assets/7e482c0c-336d-4a2f-bfc8-c904b20bc2e7)
```conf
stream {
    map $ssl_preread_server_name $name {
        mysql.test.com mysql;
        redis.test.com redis;
        default https_default_backend;
    }
    upstream mysql {
        server 10.0.0.3:3306;
    }
    upstream redis {
        server 10.0.0.4:6379;
    }
    upstream https_default_backend {
        server 127.0.0.1:443;
    }
    server {
        listen 10.0.0.1:443;
        proxy_pass $name;
        ssl_preread on;
    }
}
```

**Comment by cym1102** [comment]
map相关内容，你写在stream参数里就行了，其他upstream就用webui配就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160)




 
现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 proxy_pass $variable, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置
 QQ_1721302618332.png (view on web)
 stream {     map $ssl_preread_server_name $name {         mysql.test.com mysql;         redis.test.com redis;         default https_default_backend;     }     upstream mysql {         server 10.0.0.3:3306;     }     upstream redis {         server 10.0.0.4:6379;     }     upstream https_default_backend {         server 127.0.0.1:443;     }     server {         listen 10.0.0.1:443;         proxy_pass $name;         ssl_preread on;     } }

**Comment by ZhReimu** [comment]
> map相关内容，你写在stream参数里就行了，其他upstream就用webui配就行。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月18日(周四) 晚上7:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) 现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 proxy_pass $variable, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置 QQ_1721302618332.png (view on web) stream { map $ssl_preread_server_name $name { mysql.test.com mysql; redis.test.com redis; default https_default_backend; } upstream mysql { server 10.0.0.3:3306; } upstream redis { server 10.0.0.4:6379; } upstream https_default_backend { server 127.0.0.1:443; } server { listen 10.0.0.1:443; proxy_pass $name; ssl_preread on; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

目前确实是这么做的，但这样只能生成这种配置, 没办法做到 `proxy_pass $name;`
![image](https://github.com/user-attachments/assets/b79e700c-a065-4abf-821a-317078d76bc0)

**Comment by cym1102** [comment]
明白了，我让代理目标不是必填，这样你可以用自定义参数写proxy_pass



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160)




  
map相关内容，你写在stream参数里就行了，其他upstream就用webui配就行。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月18日(周四) 晚上7:40 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) 现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 proxy_pass $variable, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置 QQ_1721302618332.png (view on web) stream { map $ssl_preread_server_name $name { mysql.test.com mysql; redis.test.com redis; default https_default_backend; } upstream mysql { server 10.0.0.3:3306; } upstream redis { server 10.0.0.4:6379; } upstream https_default_backend { server 127.0.0.1:443; } server { listen 10.0.0.1:443; proxy_pass $name; ssl_preread on; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
目前确实是这么做的，但这样只能生成这种配置, 没办法做到 proxy_pass $name;
 image.png (view on web)

**Comment by ZhReimu** [comment]
> 明白了，我让代理目标不是必填，这样你可以用自定义参数写proxy_pass
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月18日(周四) 晚上7:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) map相关内容，你写在stream参数里就行了，其他upstream就用webui配就行。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月18日(周四) 晚上7:40 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) 现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 proxy_pass $variable, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置 QQ_1721302618332.png (view on web) stream { map $ssl_preread_server_name $name { mysql.test.com mysql; redis.test.com redis; default https_default_backend; } upstream mysql { server 10.0.0.3:3306; } upstream redis { server 10.0.0.4:6379; } upstream https_default_backend { server 127.0.0.1:443; } server { listen 10.0.0.1:443; proxy_pass $name; ssl_preread on; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 目前确实是这么做的，但这样只能生成这种配置, 没办法做到 proxy_pass $name; image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

对的，这样自由度也更高，udp 为什么没做这个限制呢

**Comment by cym1102** [comment]
那是udp的bug，不过按你这么说，现在也不算bug了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上8:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160)




  
明白了，我让代理目标不是必填，这样你可以用自定义参数写proxy_pass
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月18日(周四) 晚上7:51 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) map相关内容，你写在stream参数里就行了，其他upstream就用webui配就行。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月18日(周四) 晚上7:40 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 放开 tcp 反向代理的限制 (Issue #160) 现在的 tcp 代理必须设置一个 upstream 才能用, 似乎没办法实现 proxy_pass $variable, 这就没法使用根据域名转发或者根据 geoCountry 转发了, 比如下边的这种配置 QQ_1721302618332.png (view on web) stream { map $ssl_preread_server_name $name { mysql.test.com mysql; redis.test.com redis; default https_default_backend; } upstream mysql { server 10.0.0.3:3306; } upstream redis { server 10.0.0.4:6379; } upstream https_default_backend { server 127.0.0.1:443; } server { listen 10.0.0.1:443; proxy_pass $name; ssl_preread on; } } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 目前确实是这么做的，但这样只能生成这种配置, 没办法做到 proxy_pass $name; image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
对的，这样自由度也更高，udp 为什么没做这个限制呢

**Comment by cym1102** [comment]
4.2.1已解决
