### ISSUE TITLE
SSL not work with cloudflare.

### ISSUE THREAD

**Issue by ntccloud** [cym1102/nginxWebUI#17]
Certificate gen with token cloudflare : Good

Cer_path 👍 
pem: /home/nginxWebUI/cert/.xxx.com.fullchain.cer 
key: /home/nginxWebUI/cert/xxx.com.key

config gen ==>

load_module /usr/lib/nginx/modules/ngx_stream_module.so;
pid /home/nginxWebUI/nginx.pid;
worker_processes auto;
events {
    worker_connections  1024;
    accept_mutex on;
  }
http {
  include mime.types;
  include /home/nginxWebUI/global.d/*;
  default_type application/octet-stream;

  upstream thanks_cym1102 {
    server 192.168.31.181:2021 weight=1 fail_timeout=10s max_fails=1 ;
    server 192.168.31.181:2022 weight=1 fail_timeout=10s max_fails=1 down;
    server 192.168.31.181:2023 weight=1 fail_timeout=10s max_fails=1 backup;
  }
  server {
    server_name ntcong.com;
    listen 443 ssl http2;
    ssl_certificate /home/nginxWebUI/cert/xxx.com.fullchain.cer;
    ssl_certificate_key /home/nginxWebUI/cert/xxx.com.key;
    access_log /home/nginxWebUI/log/xxx.com_access_log;
    error_log /home/nginxWebUI/log/xxx.com_error_log;

    location / {
      proxy_pass http://thanks_cym1102;
      proxy_set_header X-Real-IP  $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
      proxy_redirect off;
    }
  }
  
}

Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://xxx.com/wp-admin/

**Comment by cym1102** [comment]
Nginx conf has no problem, maybe your wp-admin program has some code bug. 
look this https://stackoverflow.com/questions/61989976/spring-boot-error-exceeded-maxredirects-probably-stuck-in-a-redirect-loop/62001941

**Comment by ntccloud** [comment]
wp-admin not problem, i did try some nginx manager container with https://xxx.com/wp-admin/ it's OK, https work well. but when i stop some "nginx manager container" and enable NginxWebUI and then i have problem https not work with that domain, may be certificate not work? i don't know why? i used docker and setup on docker container.

**Comment by cym1102** [comment]
Point is "Exceeded maxRedirects" , maybe you should try "proxy_set_header Host host:server_port;", send port to  wp-admin

**Comment by ntccloud** [comment]
I remove proxy_set_header Host host:server_port and resolve "Exceeded maxRedirects" but, certificate not work Error: Hostname/IP does not match certificate's altnames: Host: xxx.com. is not in the cert's altnames: DNS:*.xxx.com

**Comment by cym1102** [comment]
Because&nbsp;xxx.com is not match&nbsp;*.xxx.com,&nbsp; you can use www.xxx.com or m.xxx.com etc. except xxx.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午12:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] SSL not work with cloudflare. (#17)





 
I remove proxy_set_header Host host:server_port and resolve "Exceeded maxRedirects" but, certificate not work Error: Hostname/IP does not match certificate's altnames: Host: xxx.com. is not in the cert's altnames: DNS:*.xxx.com
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ntccloud** [comment]
Thank for fast response, i have resolve this problem. exactly as you said, i remove proxy_set_header Host host:server_port; from config ssl and work well.

**Comment by cym1102** [comment]
You are welcome
