### ISSUE TITLE
docker启动修改hosts之后增加反向代理校验失败

### ISSUE THREAD

**Issue by henryfanyiye** [cym1102/nginxWebUI#19]
docker部署，修改hosts解析之后，增加对应域名的反向代理，校验失败

**Comment by cym1102** [comment]
不知道你机器环境怎么样, 可以加qq具体聊一下吗

**Comment by henryfanyiye** [comment]
系统：cenots7
使用docker部署的nginxWebUI，需要访问一个内部域名，在组主机/etc/hosts中配置了解析
然后在nginxWebUI中配置反向代理，校验文件和重新加载都报错
docker重启容器之后再次去配置就可以了
所以，是不是宿主机配置了host解析，docker中的服务识别不到

**Comment by cym1102** [comment]
当然识别不了, docker是个虚拟机, 和宿主机任何配置都隔离




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] docker启动修改hosts之后增加反向代理校验失败 (#19)





 
系统：cenots7
 使用docker部署的nginxWebUI，需要访问一个内部域名，在组主机/etc/hosts中配置了解析
 然后在nginxWebUI中配置反向代理，校验文件和重新加载都报错
 docker重启容器之后再次去配置就可以了
 所以，是不是宿主机配置了host解析，docker中的服务识别不到
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by henryfanyiye** [comment]
有什么解决方案吗，尝试挂载文件的方式，但是似乎不起作用

**Comment by cym1102** [comment]
那你就不要用docker部署嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月9日(周四) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] docker启动修改hosts之后增加反向代理校验失败 (#19)




 
有什么解决方案吗，尝试挂载文件的方式，但是似乎不起作用
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
