### ISSUE TITLE
Can you add Lua module embeds Lua into NGINX?

### ISSUE THREAD

**Issue by ntccloud** [cym1102/nginxWebUI#20]
Can you add Lua module embeds Lua into NGINX?

**Comment by cym1102** [comment]
No&nbsp; can&nbsp; not



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 11, 2021 15:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cym1102/nginxWebUI] Can you add Lua module embeds Lua into NGINX? (#20)




 
Can you add Lua module embeds Lua into NGINX?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ntccloud** [comment]
Thanks, but I think it would be better if nginxWebUI
with additional LUA module.
