### ISSUE TITLE
nginxwebui-nginxWebUi-server-1  | qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

### ISSUE THREAD

**Issue by cikichen** [cym1102/nginxWebUI#21]
不能支持arm64的CPU

MacBook M1

**Comment by cym1102** [comment]
估计是jdk的问题, 这个项目是纯java项目, 只要jdk没有问题, 一定能启动起来, 我没有m1, 没法检测




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月12日(星期二) 下午4:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] nginxwebui-nginxWebUi-server-1  | qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory (#21)





 
不能支持arm64的CPU
 
MacBook M1
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
