### ISSUE TITLE
2.8.1版本dockers运行，日志追踪功能异常

### ISSUE THREAD

**Issue by JessicaQling** [cym1102/nginxWebUI#23]
升级到2.8.1版本后，后台无法正常追踪容器内nginx日志。容器内`tail -f  /var/log/nginx/access.log`可以正常看到日志输出。
![image](https://user-images.githubusercontent.com/31532063/141734490-320c2c7d-8a0d-44e3-98a9-18dc37df77d3.png)
![image](https://user-images.githubusercontent.com/31532063/141734689-8340d03d-6ba6-402e-bf37-37aaac796492.png)

2.7.9版本的镜像是正常的。另外一个小建议，nginx日志可否作为docker容器的stdout输出，这样方便做日志收集。

**Comment by cym1102** [comment]
我先检查一下为何输出不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 下午2:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 2.8.1版本dockers运行，日志追踪功能异常 (Issue #23)





 
升级到2.8.1版本后，后台无法正常追踪容器内nginx日志。容器内tail -f  /var/log/nginx/access.log可以正常看到日志输出。
 
 
 
2.7.9版本的镜像是正常的。另外一个小建议，nginx日志可否作为docker容器的stdout输出，这样方便做日志收集。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cym1102** [comment]
找到问题了, 你更新2.8.2试试, 还有nginx日志位置都是自定义的, 不好做输出

**Comment by JessicaQling** [comment]
问题确认已解决。不考虑自定义日志路径的话，是否可以实现nginx日志输出stdout？有没有什么办法，我这边自定义构建镜像也可。不知道是不是方便提供下dockerfile？

**Comment by cym1102** [comment]
Dockerfile就在源代码里面




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 2.8.1版本dockers运行，日志追踪功能异常 (Issue #23)





 
问题确认已解决。不考虑自定义日志路径的话，是否可以实现nginx日志输出stdout？有没有什么办法，我这边自定义构建镜像也可。不知道是不是方便提供下dockerfile？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JessicaQling** [comment]
不好意思之前没注意到，感谢
