### ISSUE TITLE
控制台本身如何开启SSL？

### ISSUE THREAD

**Issue by cnpda08** [cym1102/nginxWebUI#25]
控制台本身如何开启SSL？

**Comment by cym1102** [comment]
不能开启，得依靠nginx代理开启




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午1:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 控制台本身如何开启SSL？ (Issue #25)





 
控制台本身如何开启SSL？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
