### ISSUE TITLE
有沒有海外的nginxwebui下載地址

### ISSUE THREAD

**Issue by jeromeleong** [cym1102/nginxWebUI#66]
完全下載不了😭
```
--2023-01-12 14:27:48--  http://file.nginxwebui.cn/nginxWebUI-3.4.6.jar
Resolving file.nginxwebui.cn (file.nginxwebui.cn)... 45.154.213.49
Connecting to file.nginxwebui.cn (file.nginxwebui.cn)|45.154.213.49|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29851345 (28M) [application/java-archive]
Saving to: 'nginxWebUI-3.4.6.jar'

nginxWebUI-3.4.6.jar             0%[                                                    ] 189.23K  --.-KB/s    eta 4h 28m
```

**Comment by kazma258** [comment]
同求 用了好幾個方法都不行
docker 甚至無法連線

**Comment by AlanKhTw** [comment]
不好意思，cn源速度非常慢
用新加坡伺服器只能3kb/s
能否新增海外載點呢？謝謝👍

[iMarkup_20230302_145024.jpg](https://user-images.githubusercontent.com/124500584/222352689-59170e7d-5de1-49d5-ba3a-b21695929c6e.jpg)

**Comment by cym1102** [comment]
我放一个release版到github上吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 下午2:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [cym1102/nginxWebUI] 有沒有海外的nginxwebui下載地址 (Issue #66)





 
不好意思，cn源速度非常慢
 用新加坡伺服器只能3kb/s
 能否新增海外載點呢？謝謝👍
 
iMarkup_20230302_145024.jpg

**Comment by AlanKhTw** [comment]
> 我放一个release版到github上吧
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2023年3月2日(星期四) 下午2:52
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;Re: [cym1102/nginxWebUI] 有沒有海外的nginxwebui下載地址 (Issue #66)
> 
> 
> 
> 
> 
>  
> 不好意思，cn源速度非常慢
>  用新加坡伺服器只能3kb/s
>  能否新增海外載點呢？謝謝👍
>  
> iMarkup_20230302_145024.jpg
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感激不盡，很棒的專案💯

**Comment by cym1102** [comment]
已将3.4.6 jar上传github




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 有沒有海外的nginxwebui下載地址 (Issue #66)





  
我放一个release版到github上吧
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    @.&gt;;
 发送时间:&nbsp;2023年3月2日(星期四) 下午2:52
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;Re: [cym1102/nginxWebUI] 有沒有海外的nginxwebui下載地址 (Issue #66)
 
不好意思，cn源速度非常慢
 用新加坡伺服器只能3kb/s
 能否新增海外載點呢？謝謝👍
 
iMarkup_20230302_145024.jpg
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
感激不盡，很棒的專案💯
