### ISSUE TITLE
我改了下源码增加了在renew证书之后 执行脚本reload.sh

### ISSUE THREAD

**Issue by chenxudong2020** [cym1102/nginxWebUI#80]
https://github.com/chenxudong2020/nginxWebUI.git

![image](https://github.com/cym1102/nginxWebUI/assets/61214170/0dc14257-c48e-4215-b4ab-8c5f7ab8e4cc)

![image](https://github.com/cym1102/nginxWebUI/assets/61214170/b65609fa-9c9b-44d5-a655-c12688a30057)

![image](https://github.com/cym1102/nginxWebUI/assets/61214170/cec2c749-ff5b-4151-b13f-529f4157f199)

目前我这边已经实现了需求renew证书的时候docker部署中重启 另外的一个docker容器derper

希望pr

**Comment by cym1102** [comment]
你这个reload.sh是干啥用的?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 上午9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 我改了下源码增加了在renew证书之后 执行脚本reload.sh (Issue #80)





 
https://github.com/chenxudong2020/nginxWebUI.git
 
CertController

**Comment by chenxudong2020** [comment]
> 你这个reload.sh是干啥用的?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月17日(星期三) 上午9:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 我改了下源码增加了在renew证书之后 执行脚本reload.sh (Issue #80) https://github.com/chenxudong2020/nginxWebUI.git CertController — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

自定义shell脚本   

目前我这边已经实现了需求renew证书的时候docker部署中重启 另外的一个docker容器derper

**Comment by cym1102** [comment]
你最好使用gitee上的代码进行fork, github上的代码因为我的网络环境问题, 不一定是最新的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 上午10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 我改了下源码增加了在renew证书之后 执行脚本reload.sh (Issue #80)





  
你这个reload.sh是干啥用的?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年5月17日(星期三) 上午9:20 收件人: @.&gt;; 抄送: @.&gt;; 主题: [cym1102/nginxWebUI] 我改了下源码增加了在renew证书之后 执行脚本reload.sh (Issue #80) https://github.com/chenxudong2020/nginxWebUI.git CertController — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
自定义shell脚本
 
目前我这边已经实现了需求renew证书的时候docker部署中重启 另外的一个docker容器derper

**Comment by chenxudong2020** [comment]
你可以搞个github action机器人每天自动拉取并提交

**Comment by guleng** [comment]
@cym1102 为什么nginx只有start和stop的    应该reload是刚需
